openapi: 3.0.1
info:
  title: Leasing Service
  version: 1.0
  termsOfService: "https://allane.com/terms/"
  contact:
    email: lease-service@allane.com
  license:
    name: Proprietary
    url: "https://www.allane.com"
servers:
  - url: http://localhost:8080
    description: local development server url

paths:
  /customer/{id}:
    summary: get customer for id
    get:
      tags:
        - customer
      operationId: getCustomerForId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: found customer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        404:
          description: "customer not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /vehicle/{id}:
    summary: get vehicle for id
    get:
      tags:
        - vehicle
      operationId: getVehicleForId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: found vehicle
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vehicle"
        404:
          description: "customer not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ErrorResponse:
      required:
        - httpStatusCode
        - httpReasonPhrase
        - message
        - timeStamp
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        path:
          type: string

    Customer:
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          maxLength: 50
        lastName:
          type: string
          maxLength: 50
        birthDate:
          type: string
          format: date
      required:
        - firstName
        - lastName
        - birthDate
    Vehicle:
      properties:
        id:
          type: integer
          format: int64


